name: CI

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: lint
        run: |
          yarn install
          yarn build:icons
          yarn tsm
          yarn lint:scss
          yarn build:scss
          yarn tsc
          yarn build-storybook

      - name: Lost Pixel
        id: lp
        uses: lost-pixel/lost-pixel@v2.15.0
        continue-on-error: true

      - name: Upload artefacts if Lost Pixel failed
        uses: actions/upload-artifact@v3
        if: ${{ steps.lp.outcome == 'failure' }}
        with:
          name: lost-pixel-artefacts
          path: .lostpixel

      - name: break test if Lost Pixel failed
        uses: actions/github-script@v3
        if: ${{ steps.lp.outcome == 'failure' }}
        with:
          script: |
            core.setFailed('Lost Pixel has failed, but CI has not terminated because `continue-on-error` is true. Intentionally terminate it here.')
